### ISSUE TITLE
Duplication of news articles in news.json on running the script multiple times

### ISSUE THREAD

**Issue by athityakumar** [metakgp/lord-varys#1]
@icyflame - Currently, this script is able to crawl through all news & store it in news.json file. But how do we make sure that the same news in not added multiple times to the news.json file on running the script multiple times? Can you suggest some way of marking uniqueness of a news article - say, News Headlines or something like that?

**Comment by icyflame** [comment]
Hi, so this is a common problem. In general, there are two ways to solve this, either timestamps, so, basically we note down the latest news article's timestamp, and then, next time when we fetch the news, we simply check if the timestamp of the new latest article is more than the stored timestamp, if so, we know this is a new article, and store it. Else, return.

Another method to solve this (and the one we will have to use here) is the ID based method. So, the IDs on the `iitkgp.ac.in` follow a simple pattern, an integer that is incremented by 1 for each article. So, let's say you run this script for the first time, and you see that the latest article is (say) `ID 156`, now, store this in a file (not checked into Git), that has say just one line with this integer.

Next time you run the script, again this file is checked, and you see that you have fetched upto 156. 

```
Check latest number
number > 156?
  - YES: fetch all article betweeen number and 156
  - NO: no new articles were added, return
```

BTW even `news.json` shouldn't be checked into Git, try to keep the repository as empty as possible, no data / json files, only the scripts, and a readme that explains it. (`news.json` will probably be updated again and again, and this will create unnecessary git commits which are not part of the core script's history)

**Comment by athityakumar** [comment]
Included the "id" field to fix duplication of news articles into news.json! :smile: 

As the 'json' gem works only if there are atleast 16 records in the required format in the news.json file, wouldn't it help others if we included the news.json here?

**Comment by icyflame** [comment]
Whaaaa? That doesn't make any sense. We should use a different gem _if_ that is actually a constraint.

**Comment by icyflame** [comment]
@athityakumar btw, json is not a gem but an inbuilt library in ruby. Simply requiring json without any gem should work and bring `JSON` (uppercase) into the script. I don't remember any such limitation. Any documentation that mentions this? Share a link maybe?

**Comment by athityakumar** [comment]
Tried the script on an empty news.json file and got this error - "A JSON text must contain atleast two octets"
![screenshot from 2016-06-11 12 07 42](https://cloud.githubusercontent.com/assets/17109060/15983675/5d463416-2fcd-11e6-91f8-335634694669.png)

**Comment by icyflame** [comment]
Well, obviously. Since the file doesn't exist, news_list is an empty object. And you are trying to call last on an empty object. This is solved by checking if the fileexists using `File#exists` (check the documentation for the right name of this method) and then using the list. Otherwise, initialise to an empty list and so on. (You can assign latest ID to 0 assuming that the id of news articles must have started from 0)

**Comment by icyflame** [comment]
And what that erro r means is that the news.json file must contain atleast `{ }` which is absolutely reasonable. (As that is the smallest JSON text that one can build.)

**Comment by athityakumar** [comment]
@icyflame : Actually, the absence of news.json file was never really an issue - as rescuing the error makes the program to run without any logic-issues now. If you can go through the latest push , we can close this issue. :smile:

**Comment by athityakumar** [comment]
@icyflame -  Actually, the absence of news.json file was never really an issue - as rescuing the error makes the program to run without any logic-issues now. If you can go through the latest push , we can close this issue. 😄

**Comment by icyflame** [comment]
Sure, everything looks fine! Closing this issue now, as this has been taken care of in the script.
