### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by hargup** [metakgp/lord-varys#5]
@athityakumar There is no license for this repository, please add one. Copyright is automatically granted to any code you write and unless you explicitly grant permissions in form of license people are not allowed to use this code. I prefer strong copyleft licenses like GPLv3 and AGPL, though you are free to choose a license.

**Comment by athityakumar** [comment]
cc @hargup

**Comment by raivivek** [comment]
Please add a copy of the license in `LICENSE` (plaintext, no markdown) file inside the root of the repository.

http://choosealicense.com

**Comment by hargup** [comment]
fixed with https://github.com/metakgp/lord-varys/commit/74608f4b5005264ff0b6c3bac8fe2a5b13f95be5
